export interface Product {
  id: number;
  title: string;
  price: string;
  oldPrice?: string;
  badge?: string | null;
  color: string;
  category: string;
  description?: string;
  image: string;
  // New extended attributes
  brand: string;
  sizes: string[];
  colors: string[];
  fabric: string;
  pattern: string;
  sleeveType: string;
  occasion: string;
  fitType: string;
  washCare: string;
  stockQuantity: number;
}

export const products: Product[] = [
  // Ethnic Wear (Sarees)
  {
    id: 1,
    title: "Royal Crimson Silk Saree",
    price: "₹8,999",
    oldPrice: "₹12,999",
    badge: "Exclusive",
    color: "bg-red-500",
    category: "Ethnic Wear",
    description: "A majestic crimson silk saree with intricate gold zari borders, perfect for grand occasions and bridal wear. Handcrafted with the finest silk for a regal drape.",
    image: "/images/boutique/product-1.png",
    brand: "Aura Silks",
    sizes: ["Free Size"],
    colors: ["Crimson Red", "Gold"],
    fabric: "Pure Silk",
    pattern: "Zari Woven",
    sleeveType: "N/A",
    occasion: "Wedding & Festive",
    fitType: "Regular",
    washCare: "Dry Clean Only",
    stockQuantity: 15,
  },
  {
    id: 2,
    title: "Purple Mysore Silk Saree",
    price: "₹6,499",
    badge: null,
    color: "bg-purple-600",
    category: "Ethnic Wear",
    description: "Elegant Mysore silk saree in a rich purple hue, known for its light weight and smooth texture. A timeless choice for formal events.",
    image: "/images/boutique/product-2.png",
    brand: "Mysore Heritage",
    sizes: ["Free Size"],
    colors: ["Purple"],
    fabric: "Mysore Silk",
    pattern: "Solid with Border",
    sleeveType: "N/A",
    occasion: "Formal & Festive",
    fitType: "Regular",
    washCare: "Dry Clean Only",
    stockQuantity: 22,
  },
  {
    id: 3,
    title: "Emerald Banarasi Saree",
    price: "₹11,999",
    oldPrice: "₹15,999",
    badge: "New",
    color: "bg-emerald-600",
    category: "Ethnic Wear",
    description: "Opulent Banarasi saree in emerald green, featuring traditional floral motifs and heavy gold weave. A masterpiece of Indian craftsmanship.",
    image: "/images/boutique/product-3.png",
    brand: "Banarasi Looms",
    sizes: ["Free Size"],
    colors: ["Emerald Green", "Gold"],
    fabric: "Banarasi Silk",
    pattern: "Floral Woven",
    sleeveType: "N/A",
    occasion: "Wedding & Festive",
    fitType: "Regular",
    washCare: "Dry Clean Only",
    stockQuantity: 8,
  },
  {
    id: 4,
    title: "Cotton Handloom Saree",
    price: "₹2,499",
    badge: "Bestseller",
    color: "bg-blue-300",
    category: "Ethnic Wear",
    description: "Breathable and comfortable pure cotton handloom saree for everyday elegance.",
    image: "/images/boutique/product-1.png",
    brand: "WeaveCraft",
    sizes: ["Free Size"],
    colors: ["Light Blue", "White"],
    fabric: "Pure Cotton",
    pattern: "Checked",
    sleeveType: "N/A",
    occasion: "Casual & Daily Wear",
    fitType: "Regular",
    washCare: "Hand Wash",
    stockQuantity: 40,
  },
  {
    id: 5,
    title: "Designer Ruffle Saree",
    price: "₹5,999",
    oldPrice: "₹7,999",
    badge: "Trending",
    color: "bg-pink-400",
    category: "Party Wear",
    description: "Contemporary pre-draped ruffle saree for modern parties.",
    image: "/images/boutique/product-2.png",
    brand: "Modern Diva",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Dusty Pink"],
    fabric: "Georgette",
    pattern: "Solid Ruffles",
    sleeveType: "N/A",
    occasion: "Party & Cocktail",
    fitType: "Fitted",
    washCare: "Dry Clean Only",
    stockQuantity: 30,
  },
  {
    id: 6,
    title: "Embroidered Kurti Set",
    price: "₹3,499",
    badge: "Premium",
    color: "bg-yellow-500",
    category: "Ethnic Wear",
    description: "Beautifully embroidered kurti set with matching palazzo and dupatta.",
    image: "/images/boutique/product-3.png",
    brand: "Ethnic Roots",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Mustard Yellow"],
    fabric: "Chanderi Silk",
    pattern: "Floral Embroidery",
    sleeveType: "3/4th Sleeves",
    occasion: "Festive",
    fitType: "Regular Fit",
    washCare: "Dry Clean",
    stockQuantity: 25,
  },
  {
    id: 7,
    title: "Anarkali Suit Set",
    price: "₹6,999",
    oldPrice: "₹8,999",
    badge: null,
    color: "bg-teal-600",
    category: "Ethnic Wear",
    description: "Floor-length Anarkali suit with intricate thread work.",
    image: "/images/boutique/product-1.png",
    brand: "Royal Wardrobe",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Teal Green"],
    fabric: "Silk Blend",
    pattern: "Embroidered",
    sleeveType: "Full Sleeves",
    occasion: "Wedding Guest",
    fitType: "Flared",
    washCare: "Dry Clean Only",
    stockQuantity: 12,
  },
  {
    id: 8,
    title: "Festive Lehenga Choli",
    price: "₹14,999",
    badge: "Exclusive",
    color: "bg-orange-500",
    category: "Ethnic Wear",
    description: "Heavy embellished lehenga choli for festive celebrations.",
    image: "/images/boutique/product-2.png",
    brand: "Bridal Bliss",
    sizes: ["M", "L", "XL"],
    colors: ["Orange", "Gold"],
    fabric: "Raw Silk",
    pattern: "Zari & Stone Work",
    sleeveType: "Short Sleeves",
    occasion: "Bridal & Festive",
    fitType: "Regular",
    washCare: "Dry Clean Only",
    stockQuantity: 5,
  },
  
  // Western Wear
  {
    id: 9,
    title: "Floral Maxi Dress",
    price: "₹2,999",
    oldPrice: "₹3,999",
    badge: "Summer",
    color: "bg-pink-200",
    category: "Western Wear",
    description: "Breezy floral maxi dress perfect for summer brunches.",
    image: "/images/boutique/product-3.png",
    brand: "Urban Chic",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blush Pink", "White"],
    fabric: "Chiffon",
    pattern: "Floral Print",
    sleeveType: "Sleeveless",
    occasion: "Casual & Resort",
    fitType: "Relaxed",
    washCare: "Machine Wash Cold",
    stockQuantity: 50,
  },
  {
    id: 10,
    title: "Classic White Shirt",
    price: "₹1,499",
    badge: "Essential",
    color: "bg-white",
    category: "Office Wear",
    description: "Crisp white button-down shirt for a professional look.",
    image: "/images/boutique/product-1.png",
    brand: "Corporate Edge",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White"],
    fabric: "Cotton Blend",
    pattern: "Solid",
    sleeveType: "Full Sleeves",
    occasion: "Formal & Office",
    fitType: "Tailored Fit",
    washCare: "Machine Wash",
    stockQuantity: 100,
  },
  {
    id: 11,
    title: "Ribbed Crop Top",
    price: "₹899",
    badge: null,
    color: "bg-black",
    category: "Western Wear",
    description: "Versatile ribbed crop top for casual outings.",
    image: "/images/boutique/product-2.png",
    brand: "Street Style",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Black", "White", "Olive"],
    fabric: "Cotton Rib",
    pattern: "Solid",
    sleeveType: "Short Sleeves",
    occasion: "Casual",
    fitType: "Bodycon",
    washCare: "Machine Wash",
    stockQuantity: 75,
  },
  {
    id: 12,
    title: "Evening Cocktail Dress",
    price: "₹4,999",
    oldPrice: "₹6,999",
    badge: "Premium",
    color: "bg-blue-800",
    category: "Party Wear",
    description: "Elegant sequin evening gown for special nights.",
    image: "/images/boutique/product-3.png",
    brand: "Glamour Nights",
    sizes: ["S", "M", "L"],
    colors: ["Midnight Blue", "Black"],
    fabric: "Sequin & Net",
    pattern: "Embellished",
    sleeveType: "Sleeveless",
    occasion: "Party",
    fitType: "Slim Fit",
    washCare: "Dry Clean Only",
    stockQuantity: 18,
  },
  {
    id: 13,
    title: "Denim Jacket",
    price: "₹2,499",
    badge: null,
    color: "bg-blue-400",
    category: "Western Wear",
    description: "Classic blue denim jacket with a relaxed fit.",
    image: "/images/boutique/product-1.png",
    brand: "Denim Co.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Light Blue Wash"],
    fabric: "Denim",
    pattern: "Solid",
    sleeveType: "Full Sleeves",
    occasion: "Casual",
    fitType: "Relaxed",
    washCare: "Machine Wash",
    stockQuantity: 60,
  },
  {
    id: 14,
    title: "Chic Jumpsuit",
    price: "₹3,299",
    badge: "Trending",
    color: "bg-red-600",
    category: "Western Wear",
    description: "Tailored jumpsuit for a seamless fashion statement.",
    image: "/images/boutique/product-2.png",
    brand: "Modern Diva",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Red", "Black"],
    fabric: "Crepe",
    pattern: "Solid",
    sleeveType: "Sleeveless",
    occasion: "Party & Casual",
    fitType: "Regular",
    washCare: "Machine Wash Cold",
    stockQuantity: 35,
  },

  // Bottom Wear
  {
    id: 15,
    title: "High-Waist Wide Leg Jeans",
    price: "₹2,199",
    oldPrice: "₹2,999",
    badge: "Popular",
    color: "bg-blue-500",
    category: "Bottom Wear",
    description: "Trendy wide-leg jeans for a vintage inspired look.",
    image: "/images/boutique/product-3.png",
    brand: "Denim Co.",
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Medium Wash", "Light Wash"],
    fabric: "Cotton Denim",
    pattern: "Solid",
    sleeveType: "N/A",
    occasion: "Casual",
    fitType: "Wide Leg",
    washCare: "Machine Wash",
    stockQuantity: 80,
  },
  {
    id: 16,
    title: "Formal Trousers",
    price: "₹1,899",
    badge: null,
    color: "bg-gray-800",
    category: "Office Wear",
    description: "Smart fit formal trousers for work.",
    image: "/images/boutique/product-1.png",
    brand: "Corporate Edge",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Charcoal Grey", "Navy", "Black"],
    fabric: "Polyester Viscose",
    pattern: "Solid",
    sleeveType: "N/A",
    occasion: "Formal",
    fitType: "Straight Fit",
    washCare: "Machine Wash",
    stockQuantity: 45,
  },
  {
    id: 17,
    title: "Pleated Midi Skirt",
    price: "₹1,699",
    badge: "New",
    color: "bg-pink-300",
    category: "Bottom Wear",
    description: "Feminine pleated midi skirt with elasticated waist.",
    image: "/images/boutique/product-2.png",
    brand: "Urban Chic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blush Pink", "Mint Green"],
    fabric: "Georgette",
    pattern: "Pleated",
    sleeveType: "N/A",
    occasion: "Casual & Semi-Formal",
    fitType: "Flared",
    washCare: "Machine Wash Cold",
    stockQuantity: 55,
  },
  {
    id: 18,
    title: "Printed Palazzo Pants",
    price: "₹1,299",
    badge: null,
    color: "bg-yellow-200",
    category: "Bottom Wear",
    description: "Comfortable and flowy palazzo pants with bohemian prints.",
    image: "/images/boutique/product-3.png",
    brand: "Boho Touch",
    sizes: ["Free Size"],
    colors: ["Multicolor"],
    fabric: "Rayon",
    pattern: "Printed",
    sleeveType: "N/A",
    occasion: "Casual",
    fitType: "Loose Fit",
    washCare: "Hand Wash",
    stockQuantity: 40,
  },

  // Office Wear
  {
    id: 19,
    title: "Tailored Blazer",
    price: "₹3,999",
    oldPrice: "₹4,999",
    badge: "Premium",
    color: "bg-black",
    category: "Office Wear",
    description: "A well-tailored black blazer that adds power to your office attire.",
    image: "/images/boutique/product-1.png",
    brand: "Corporate Edge",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy Blue"],
    fabric: "Poly Blend",
    pattern: "Solid",
    sleeveType: "Full Sleeves",
    occasion: "Formal",
    fitType: "Slim Fit",
    washCare: "Dry Clean",
    stockQuantity: 25,
  },
  {
    id: 20,
    title: "Pencil Skirt",
    price: "₹1,499",
    badge: null,
    color: "bg-gray-600",
    category: "Office Wear",
    description: "Classic pencil skirt for a sharp professional look.",
    image: "/images/boutique/product-2.png",
    brand: "Corporate Edge",
    sizes: ["28", "30", "32", "34"],
    colors: ["Grey", "Black"],
    fabric: "Cotton Blend",
    pattern: "Solid",
    sleeveType: "N/A",
    occasion: "Formal",
    fitType: "Slim Fit",
    washCare: "Machine Wash",
    stockQuantity: 30,
  },
  {
    id: 21,
    title: "Silk Wrap Top",
    price: "₹2,299",
    badge: "Trending",
    color: "bg-emerald-500",
    category: "Office Wear",
    description: "Luxurious silk wrap top perfect for desk to dinner.",
    image: "/images/boutique/product-3.png",
    brand: "Urban Chic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Emerald Green", "Maroon"],
    fabric: "Satin Silk",
    pattern: "Solid",
    sleeveType: "Full Sleeves",
    occasion: "Formal & Party",
    fitType: "Regular",
    washCare: "Dry Clean Only",
    stockQuantity: 20,
  },

  // Party Wear
  {
    id: 22,
    title: "Shimmer Bodycon Dress",
    price: "₹3,599",
    badge: "Bestseller",
    color: "bg-amber-500",
    category: "Party Wear",
    description: "Make a statement in this stunning shimmer bodycon dress.",
    image: "/images/boutique/product-1.png",
    brand: "Glamour Nights",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Gold", "Silver"],
    fabric: "Lurex",
    pattern: "Shimmer",
    sleeveType: "Full Sleeves",
    occasion: "Party",
    fitType: "Bodycon",
    washCare: "Dry Clean",
    stockQuantity: 40,
  },
  {
    id: 23,
    title: "Velvet Gown",
    price: "₹7,999",
    oldPrice: "₹9,999",
    badge: "Exclusive",
    color: "bg-red-900",
    category: "Party Wear",
    description: "Luxurious velvet gown with a thigh-high slit.",
    image: "/images/boutique/product-2.png",
    brand: "Glamour Nights",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Maroon", "Navy Blue"],
    fabric: "Velvet",
    pattern: "Solid",
    sleeveType: "Sleeveless",
    occasion: "Evening & Party",
    fitType: "Regular",
    washCare: "Dry Clean",
    stockQuantity: 15,
  },

  // Seasonal Collections
  {
    id: 24,
    title: "Woolen Trench Coat",
    price: "₹6,499",
    badge: "Winter",
    color: "bg-orange-200",
    category: "Seasonal Collections",
    description: "Classic beige trench coat for chilly winter days.",
    image: "/images/boutique/product-3.png",
    brand: "Winter Essentials",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Beige", "Camel"],
    fabric: "Wool Blend",
    pattern: "Solid",
    sleeveType: "Full Sleeves",
    occasion: "Winter Wear",
    fitType: "Regular Fit",
    washCare: "Dry Clean Only",
    stockQuantity: 28,
  },
  {
    id: 25,
    title: "Linen Summer Tunic",
    price: "₹1,999",
    badge: "Summer",
    color: "bg-blue-100",
    category: "Seasonal Collections",
    description: "Breathable pure linen tunic for the summer heat.",
    image: "/images/boutique/product-1.png",
    brand: "Summer Breez",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Powder Blue", "White", "Lemon Yellow"],
    fabric: "Pure Linen",
    pattern: "Solid",
    sleeveType: "3/4th Sleeves",
    occasion: "Casual Summer",
    fitType: "Relaxed Fit",
    washCare: "Machine Wash",
    stockQuantity: 65,
  },
  {
    id: 26,
    title: "Chunky Knit Sweater",
    price: "₹2,199",
    oldPrice: "₹2,999",
    badge: "Winter",
    color: "bg-red-300",
    category: "Seasonal Collections",
    description: "Cozy oversized chunky knit sweater.",
    image: "/images/boutique/product-2.png",
    brand: "Winter Essentials",
    sizes: ["S", "M", "L"],
    colors: ["Dusty Rose", "Cream"],
    fabric: "Acrylic Blend",
    pattern: "Textured Knit",
    sleeveType: "Full Sleeves",
    occasion: "Casual Winter",
    fitType: "Oversized",
    washCare: "Hand Wash Cold",
    stockQuantity: 40,
  },
  {
    id: 27,
    title: "Cotton Kaftan",
    price: "₹1,499",
    badge: "Summer",
    color: "bg-green-200",
    category: "Seasonal Collections",
    description: "Relaxed fit cotton kaftan dress for lazy summer afternoons.",
    image: "/images/boutique/product-3.png",
    brand: "Summer Breez",
    sizes: ["Free Size"],
    colors: ["Mint Green", "Peach"],
    fabric: "Cotton",
    pattern: "Printed",
    sleeveType: "Short Sleeves",
    occasion: "Loungewear",
    fitType: "Loose",
    washCare: "Machine Wash",
    stockQuantity: 50,
  },
  {
    id: 28,
    title: "Festive Silk Kurta Set",
    price: "₹4,599",
    badge: "Festive",
    color: "bg-pink-600",
    category: "Seasonal Collections",
    description: "Bright and vibrant silk kurta set for Diwali and weddings.",
    image: "/images/boutique/product-1.png",
    brand: "Festive Charm",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Fuchsia Pink"],
    fabric: "Art Silk",
    pattern: "Embroidered",
    sleeveType: "3/4th Sleeves",
    occasion: "Festive",
    fitType: "Regular",
    washCare: "Dry Clean Only",
    stockQuantity: 20,
  },
  {
    id: 29,
    title: "Puffer Jacket",
    price: "₹3,999",
    badge: "Winter",
    color: "bg-gray-900",
    category: "Seasonal Collections",
    description: "Lightweight yet warm puffer jacket for extreme winters.",
    image: "/images/boutique/product-2.png",
    brand: "Winter Essentials",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Navy"],
    fabric: "Nylon",
    pattern: "Quilted",
    sleeveType: "Full Sleeves",
    occasion: "Winter Wear",
    fitType: "Regular",
    washCare: "Machine Wash",
    stockQuantity: 30,
  },
  {
    id: 30,
    title: "Georgette Sarees Set",
    price: "₹3,499",
    badge: "Trending",
    color: "bg-purple-300",
    category: "Ethnic Wear",
    description: "Lightweight and flowy georgette sarees with a modern touch.",
    image: "/images/boutique/product-3.png",
    brand: "Aura Silks",
    sizes: ["Free Size"],
    colors: ["Lavender"],
    fabric: "Georgette",
    pattern: "Printed",
    sleeveType: "N/A",
    occasion: "Festive & Casual",
    fitType: "Regular",
    washCare: "Dry Clean",
    stockQuantity: 40,
  }
];

// Let's create duplicates up to 50 for the sake of mockup scale, mapping them appropriately.
// Adding 20 more variations
Array.from({ length: 20 }).forEach((_, i) => {
  products.push({
    ...products[i % 30],
    id: 31 + i,
    title: `${products[i % 30].title} Variation ${i + 1}`,
    price: products[i % 30].price,
    stockQuantity: Math.floor(Math.random() * 50) + 5,
  });
});
